# Generated by Django 5.1.15 on 2026-08-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosha_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doshaprofile',
            name='secondary_dosha',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
