# Generated by Django 6.1 on 2026-08-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('steward', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HerbAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_herb', models.CharField(db_index=True, max_length=120)),
                ('alias', models.CharField(db_index=True, max_length=120)),
                ('language', models.CharField(default='common', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
            ],
            options={
                'unique_together': {('canonical_herb', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='InteractionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_a', models.CharField(db_index=True, max_length=120)),
                ('herb_b_or_drug', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('herb_drug', 'herb_drug'), ('herb_herb', 'herb_herb')], default='herb_drug', max_length=16)),
                ('interaction_type', models.CharField(blank=True, max_length=64)),
                ('mechanism', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('severity', models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('SEVERE', 'SEVERE')], max_length=16)),
                ('evidence', models.CharField(choices=[('VALIDATED', 'VALIDATED'), ('PROBABLE', 'PROBABLE'), ('THEORETICAL', 'THEORETICAL'), ('CLASSICAL', 'CLASSICAL'), ('ANECDOTAL', 'ANECDOTAL')], max_length=16)),
                ('dose_threshold', models.CharField(blank=True, max_length=64)),
                ('context_tag', models.CharField(blank=True, choices=[('', 'any'), ('pregnancy', 'pregnancy'), ('pediatric', 'pediatric (<12y)'), ('renal', 'renal impairment'), ('diabetes', 'diabetes')], default='', max_length=32)),
                ('source_uri', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guardrails.ruleversion')),
            ],
            options={
                'indexes': [models.Index(fields=['herb_a', 'herb_b_or_drug'], name='guardrails__herb_a_87cb87_idx')],
            },
        ),
    ]
