# Generated by Django 6.1 on 2026-08-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('interactions_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='guardrail_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions_log.guardraildecision'),
        ),
    ]
