# Generated by Django 6.1 on 2026-08-18 14:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DinacharyaRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('season', models.CharField(choices=[('vasant', 'vasant'), ('grishma', 'grishma'), ('varsha', 'varsha'), ('sharad', 'sharad'), ('hemant', 'hemant'), ('shishir', 'shishir')], max_length=16)),
                ('engine_version', models.CharField(default='1.0.0', max_length=16)),
                ('inputs_snapshot', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinacharya_recs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoutineActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_day', models.CharField(max_length=32)),
                ('start', models.TimeField()),
                ('end', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('reasons', models.JSONField(default=list)),
                ('citations', models.JSONField(default=list)),
                ('dosha_target', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dinacharya.dinacharyarecommendation')),
            ],
            options={
                'ordering': ['order', 'start'],
            },
        ),
    ]
