# Generated by Django 6.1 on 2026-08-18 14:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy', models.FloatField(default=0.0)),
                ('source', models.CharField(default='gps', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(db_index=True)),
                ('lon', models.FloatField()),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(default='openweather', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon', 'fetched_at'], name='weather_wea_lat_dc5f34_idx')],
            },
        ),
    ]
