# Generated by Django 6.1 on 2026-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weathersnapshot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='place_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
